name: flutter_bluetooth_serial
version: 0.5.1
description: Flutter basic implementation for Classical Bluetooth (only RFCOMM for now).
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.github.edufolly.flutterbluetoothserial
        pluginClass: FlutterBluetoothSerialPlugin
